CREATE TABLE `charging_pile` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '充电桩ID',
  `pile_code` varchar(50) NOT NULL COMMENT '充电桩编号',
  `pile_name` varchar(100) NOT NULL COMMENT '充电桩名称',
  `station_id` bigint DEFAULT NULL COMMENT '所属充电站ID',
  `brand_id` bigint DEFAULT NULL COMMENT '品牌ID',
  `model_id` bigint DEFAULT NULL COMMENT '型号ID',
  `pile_type` varchar(1) DEFAULT '1' COMMENT '充电桩类型（1-直流 2-交流）',
  `rated_power` decimal(10,2) DEFAULT '0.00' COMMENT '额定功率(kW)',
  `voltage` decimal(10,2) DEFAULT '0.00' COMMENT '额定电压(V)',
  `current` decimal(10,2) DEFAULT '0.00' COMMENT '额定电流(A)',
  `connector_type` varchar(50) DEFAULT NULL COMMENT '接口类型',
  `status` varchar(1) DEFAULT '0' COMMENT '状态（0-空闲 1-使用中 2-故障 3-离线）',
  `location` varchar(255) DEFAULT NULL COMMENT '安装位置',
  `longitude` decimal(10,6) DEFAULT NULL COMMENT '经度',
  `latitude` decimal(10,6) DEFAULT NULL COMMENT '纬度',
  `ip_address` varchar(50) DEFAULT NULL COMMENT 'IP地址',
  `port` int DEFAULT NULL COMMENT '端口号',
  `protocol` varchar(50) DEFAULT 'ModbusTCP' COMMENT '通讯协议',
  `last_online_time` datetime DEFAULT NULL COMMENT '最后在线时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pile_code` (`pile_code`),
  KEY `idx_station_id` (`station_id`),
  KEY `idx_brand_id` (`brand_id`),
  KEY `idx_model_id` (`model_id`),
  KEY `idx_status` (`status`),
  KEY `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='充电桩信息表';

INSERT INTO `charging_pile` VALUES (1,'CP001','充电桩1号',1,1,1,'1',150.00,0.00,0.00,NULL,'0',NULL,NULL,NULL,NULL,NULL,'ModbusTCP',NULL,NULL,'0','','2026-04-13 17:21:18','',NULL),(2,'CP002','充电桩2号',1,1,2,'1',120.00,0.00,0.00,NULL,'0',NULL,NULL,NULL,NULL,NULL,'ModbusTCP',NULL,NULL,'0','','2026-04-13 17:21:18','',NULL),(3,'CP003','充电桩3号',1,2,3,'1',100.00,0.00,0.00,NULL,'0',NULL,NULL,NULL,NULL,NULL,'ModbusTCP',NULL,NULL,'0','','2026-04-13 17:21:18','',NULL),(4,'CP004','充电桩4号',2,2,4,'1',80.00,0.00,0.00,NULL,'0',NULL,NULL,NULL,NULL,NULL,'ModbusTCP',NULL,NULL,'0','','2026-04-13 17:21:18','',NULL),(5,'CP005','充电桩5号',2,3,5,'1',120.00,0.00,0.00,NULL,'0',NULL,NULL,NULL,NULL,NULL,'ModbusTCP',NULL,NULL,'0','','2026-04-13 17:21:18','',NULL);
