import {
  ApartmentOutlined,
  AreaChartOutlined,
  AlarmOutlined,
  AppstoreOutlined,
  BarChartOutlined,
  BankOutlined,
  BookOutlined,
  BoxPlotOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CloudServerOutlined,
  CompassOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DesktopOutlined,
  DollarOutlined,
  EnvironmentOutlined,
  FileExcelOutlined,
  FileTextOutlined,
  FundProjectionScreenOutlined,
  GlobalOutlined,
  HddOutlined,
  HighlightOutlined,
  HomeOutlined,
  IdcardOutlined,
  LineChartOutlined,
  LoginOutlined,
  MedicineBoxOutlined,
  MenuOutlined,
  MonitorOutlined,
  NotificationOutlined,
  PoweroffOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SettingOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  UserOutlined,
  UsergroupAddOutlined,
  WarningOutlined,
} from '@ant-design/icons-vue'

const iconMap: Record<string, any> = {
  'data-board': DatabaseOutlined,
  alarm: AlarmOutlined,
  apartment: ApartmentOutlined,
  'area-chart': AreaChartOutlined,
  bar-chart: BarChartOutlined,
  battery: HddOutlined,
  book: BookOutlined,
  'box-plot': BoxPlotOutlined,
  calculator: CalculatorOutlined,
  calendar: CalendarOutlined,
  charge: PoweroffOutlined,
  'chart': BarChartOutlined,
  'cloud-server': CloudServerOutlined,
  compass: CompassOutlined,
  dashboard: DashboardOutlined,
  database: DatabaseOutlined,
  desktop: DesktopOutlined,
  dictionary: BookOutlined,
  dollar: DollarOutlined,
  environment: EnvironmentOutlined,
  efficiency: TrophyOutlined,
  equipment: AppstoreOutlined,
  'file-excel': FileExcelOutlined,
  'file-text': FileTextOutlined,
  global: GlobalOutlined,
  home: HomeOutlined,
  hospital: MedicineBoxOutlined,
  'office-building': BankOutlined,
  idcard: IdcardOutlined,
  lightbulb: BulbOutlined,
  line-chart: LineChartOutlined,
  login: LoginOutlined,
  log: FileTextOutlined,
  menu: MenuOutlined,
  monitor: MonitorOutlined,
  notification: NotificationOutlined,
  scan: ScanOutlined,
  schedule: ScheduleOutlined,
  setting: SettingOutlined,
  'solar-power': FundProjectionScreenOutlined,
  sun: HighlightOutlined,
  team: TeamOutlined,
  thunderbolt: ThunderboltOutlined,
  tool: ToolOutlined,
  'trend-chart': LineChartOutlined,
  user: UserOutlined,
  'usergroup-add': UsergroupAddOutlined,
  warning: WarningOutlined,
  wrench: ToolOutlined,
}

export function getMenuIcon(name?: string) {
  if (!name) return undefined
  return iconMap[name]
}